lib/pxblog_web/router.ex
defmodule PxblogWeb.Router do
  use PxblogWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug PxblogWeb.CurrentUserPlug

  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", PxblogWeb do
    pipe_through :browser

    get "/", PageController, :index



    resources "/users", UserController do
      resources "/posts", PostController
    end

    resources "/posts", PostController, only: [:index]

    resources "/posts", PostController, only: [] do
      resources "/comments", CommentController, only: [:create, :delete, :update]
    end

    resources "/sessions", SessionController, only: [:new, :create, :delete]

  end

  # Other scopes may use custom stacks.
  # scope "/api", PxblogWeb do
  #   pipe_through :api
  # end
end

lib/pxblog/posts.ex
defmodule Pxblog.Posts do
  @moduledoc """
  The Posts context.
  """

  import Ecto.Query, warn: false
  alias Pxblog.Repo

  alias Pxblog.Posts.Post

  @doc """
  Returns the list of posts.

  ## Examples

      iex> list_posts()
      [%Post{}, ...]

  """
  def list_posts do
    Repo.all(Post)
  end

  @doc """
  Gets a single post.

  Raises `Ecto.NoResultsError` if the Post does not exist.

  ## Examples

      iex> get_post!(123)
      %Post{}

      iex> get_post!(456)
      ** (Ecto.NoResultsError)

  """
  def get_post!(id), do: Repo.get!(Post, id)

  @doc """
  Creates a post.

  ## Examples

      iex> create_post(%{field: value})
      {:ok, %Post{}}

      iex> create_post(%{field: bad_value})
      {:error, %Ecto.Changeset{}}

  """
  def create_post(attrs \\ %{}) do
    %Post{}
    |> Post.changeset(attrs)
    |> Repo.insert()
  end

  @doc """
  Updates a post.

  ## Examples

      iex> update_post(post, %{field: new_value})
      {:ok, %Post{}}

      iex> update_post(post, %{field: bad_value})
      {:error, %Ecto.Changeset{}}

  """
  def update_post(%Post{} = post, attrs) do
    post
    |> Post.changeset(attrs)
    |> Repo.update()
  end

  @doc """
  Deletes a post.

  ## Examples

      iex> delete_post(post)
      {:ok, %Post{}}

      iex> delete_post(post)
      {:error, %Ecto.Changeset{}}

  """
  def delete_post(%Post{} = post) do
    Repo.delete(post)
  end

  @doc """
  Returns an `%Ecto.Changeset{}` for tracking post changes.

  ## Examples

      iex> change_post(post)
      %Ecto.Changeset{source: %Post{}}

  """
  def change_post(%Post{} = post) do
    Post.changeset(post, %{})
  end
end

lib/pxblog/posts/post.ex
defmodule Pxblog.Posts.Post do
  use Ecto.Schema
  import Ecto.Changeset

  schema "posts" do
    field :body, :string
    field :title, :string
    belongs_to :user, Pxblog.Accounts.User
    has_many :comments, Pxblog.Comment

    timestamps()
  end

  @doc false
  def changeset(post, attrs \\ %{}) do
    post
    |> cast(attrs, [:title, :body])
    |> validate_required([:title, :body])
    |> strip_unsafe_body(attrs)
  end

  defp strip_unsafe_body(model, %{"body" => nil}) do
    model
  end

  defp strip_unsafe_body(model, %{"body" => body}) do
    {:safe, clean_body} = Phoenix.HTML.html_escape(body)
    model |> put_change(:body, clean_body)
  end

  defp strip_unsafe_body(model, _) do
    model
  end
end

lib/pxblog_web/controllers/post_controller.ex
defmodule PxblogWeb.PostController do
  use PxblogWeb, :controller

  import Ecto
  import Ecto.Query

  alias Pxblog.Posts
  alias Pxblog.Posts.Post
  alias Pxblog.Repo
  alias Pxblog.Comment

  plug :assign_user when not action in [:index]
  plug :authorize_user when action in [:new, :create, :update, :edit, :delete]
  plug :set_authorization_flag

  def index(conn, %{"user_id" => _user_id}) do
    conn = assign_user(conn, nil)
    if conn.assigns[:user] do
      posts = Repo.all(assoc(conn.assigns[:user], :posts)) |> Repo.preload(:user)
      render(conn, "index.html", posts: posts)
    else
      conn
    end
  end

  def index(conn, _params) do
    posts = Repo.all(from p in Post,
                       limit: 5,
                       order_by: [desc: :inserted_at],
                       preload: [:user])
    render(conn, "index.html", posts: posts)
  end

  def new(conn, params) do
    changeset =
          conn.assigns[:user]
          |> build_assoc(:posts)
          |> Post.changeset(params)

    render(conn, "new.html", changeset: changeset)
  end

  def create(conn, %{"post" => post_params}) do
    changeset =
      conn.assigns[:user]
      |> build_assoc(:posts)
      |> Post.changeset(post_params)

    case Repo.insert(changeset) do
      {:ok, _post} ->
        conn
        |> put_flash(:info, "Post created successfully.")
        |> redirect(to: Routes.user_post_path(conn, :index, conn.assigns[:user]))

      {:error, %Ecto.Changeset{} = changeset} ->
        render(conn, "new.html", changeset: changeset)
    end
  end

  def show(conn, %{"id" => id}) do
    post = Repo.get!(assoc(conn.assigns[:user], :posts), id)
    |> Repo.preload(:comments)

    comment_changeset = post
      |> build_assoc(:comments)
      |> Comment.changeset()
    render(conn, "show.html", post: post, comment_changeset: comment_changeset)
  end

  def edit(conn, %{"id" => id}) do
    post = Repo.get!(assoc(conn.assigns[:user], :posts), id)
    changeset = Posts.change_post(post)
    render(conn, "edit.html", post: post, changeset: changeset)
  end

  def update(conn, %{"id" => id, "post" => post_params}) do
    post = Repo.get!(assoc(conn.assigns[:user], :posts), id)
    changeset = Post.changeset(post, post_params)
    case Repo.update(changeset) do
      {:ok, post} ->
        conn
        |> put_flash(:info, "Post updated successfully.")
        |> redirect(to: Routes.user_post_path(conn, :show, conn.assigns[:user], post))

      {:error, %Ecto.Changeset{} = changeset} ->
        render(conn, "edit.html", post: post, changeset: changeset)
    end
  end

  def delete(conn, %{"id" => id}) do
    post = Repo.get!(assoc(conn.assigns[:user], :posts), id)
    Repo.delete!(post)
    conn
    |> put_flash(:info, "Post deleted successfully.")
    |> redirect(to: Routes.user_post_path(conn, :index, conn.assigns[:user]))
  end

  defp assign_user(conn, _opts) do
    case conn.params do
      %{"user_id" => user_id} ->
        case Repo.get(Pxblog.Accounts.User, user_id) do
          nil -> invalid_user(conn)
          user -> assign(conn, :user, user)
        end
      _ -> invalid_user(conn)
    end
  end

  defp invalid_user(conn) do
    conn
    |> put_flash(:error, "Invalid user!")
    |> redirect(to: Routes.page_path(conn, :index))
    |> halt()
  end

  defp authorize_user(conn, _opts) do
    if is_authorized_user?(conn) do
      conn
    else
      conn
      |> put_flash(:error, "You are not authorized to modify that post!")
      |> redirect(to: Routes.page_path(conn, :index))
      |> halt
    end
  end

  defp is_authorized_user?(conn) do
    user = get_session(conn, :current_user)
    (user && (Integer.to_string(user.id) == conn.params["user_id"] || Pxblog.RoleChecker.is_admin?(user)))
  end

  defp set_authorization_flag(conn, _opts) do
    assign(conn, :author_or_admin, is_authorized_user?(conn))
  end

end

lib/pxblog_web/views/post_view.ex
defmodule PxblogWeb.PostView do
  use PxblogWeb, :view

  def markdown(body) do
    body
    |> Earmark.as_html!
    |> raw
  end
end

lib/pxblog_web/templates/post/edit.html.eex
<h1>Edit Post</h1>

<%= render "form.html", Map.put(assigns, :action, Routes.user_post_path(@conn, :update, @user, @post)) %>

<span><%= link "Back", to: Routes.user_post_path(@conn, :index, @user) %></span>

lib/pxblog_web/templates/post/form.html.eex
<%= form_for @changeset, @action, fn f -> %>
  <%= if @changeset.action do %>
    <div class="alert alert-danger">
      <p>Oops, something went wrong! Please check the errors below.</p>
    </div>
  <% end %>

  <%= label f, :title %>
  <%= text_input f, :title %>
  <%= error_tag f, :title %>

  <%= label f, :body %>
  <%= textarea f, :body, class: "form-control", id: "body-editor" %>
  <%= error_tag f, :body %>

  <div>
    <%= submit "Save" %>
  </div>
<% end %>

<link rel="stylesheet" href="//cdn.jsdelivr.net/simplemde/latest/simplemde.min.css">
<script src="//cdn.jsdelivr.net/simplemde/latest/simplemde.min.js"></script>
<script>var simplemde = new SimpleMDE();</script>

lib/pxblog_web/templates/post/index.html.eex
<div class="row">
  <div class="small-10 columns">
    <h1>Posts</h1>
  </div>
  <div class="small-2 columns text-right">
    <%= if current_user = @conn.assigns[:current_user] do %>
      <%= link "New post", to: Routes.user_post_path(@conn, :new, current_user.id), class: "button expanded large" %>
    <% end %>
  </div>
</div>

<%= for post <- @posts do %>
  <div class="row post">
    <div class="small-12 columns title">
      <h3><%= post.title %></h3>
    </div>
    <div class="small-12 columns">
      <small>
        Posted on <%= post.inserted_at %> by <%= link post.user.username, to: Routes.user_post_path(@conn, :index, post.user) %>
      </small>
    </div>
    <div class="small-12 columns">
      <%= markdown(post.body) %>
    </div>
    <%= if current_user = @conn.assigns[:current_user] do %>
      <div class="small-12 medium-4 columns">
        <%= link "Show", to: Routes.user_post_path(@conn, :show, post.user, post), class: "button expanded" %>
      </div>
      <div class="small-12 medium-4 columns">
        <%= link "Edit", to: Routes.user_post_path(@conn, :edit, post.user, post), class: "button warning expanded" %>
      </div>
      <div class="small-12 medium-4 columns">
        <%= link "Delete", to: Routes.user_post_path(@conn, :delete, post.user, post), method: :delete, data: [confirm: "Are you sure?"], class: "button alert expanded" %>
      </div>
    <% end %>
  </div>
<% end %>

<%# <span><%= link "New Post", to: Routes.user_post_path(@conn, :new, @user) %></span> 

lib/pxblog_web/templates/post/new.html.eex
<h1>New Post</h1>

<%= render "form.html", Map.put(assigns, :action, Routes.user_post_path(@conn, :create, @user)) %>

<span><%= link "Back", to: Routes.user_post_path(@conn, :index, @user) %></span>

lib/pxblog_web/templates/post/show.html.eex
<input type="hidden" id="post-id" value="<%= @post.id %>">

<h1>Show Post</h1>

<ul>

  <li>
    <strong>Title:</strong>
    <%= @post.title %>
  </li>

  <li>
    <strong>Body:</strong>
    <%= markdown(@post.body) %> 
  </li>
</ul>

<div class="comments">
  <h2> Comments </h2>
  <%= for comment <- @post.comments do %>
    <%= render PxblogWeb.CommentView, "comment.html", comment: comment, author_or_admin: @conn.assigns[:author_or_admin],
      conn: @conn,
      post: @post %>
  <% end %>
</div>

<h3> New Comment </h3>

<%= render PxblogWeb.CommentView, "form.html", changeset: @comment_changeset, action: Routes.post_comment_path(@conn, :create, @post)%>


<span><%= link "Edit", to: Routes.user_post_path(@conn, :edit, @user, @post) %></span>
<span><%= link "Back", to: Routes.user_post_path(@conn, :index, @user) %></span>