lib/pxblog_web/router.ex
defmodule PxblogWeb.Router do
  use PxblogWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug PxblogWeb.CurrentUserPlug

  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", PxblogWeb do
    pipe_through :browser

    get "/", PageController, :index



    resources "/users", UserController do
      resources "/posts", PostController
    end

    resources "/posts", PostController, only: [:index]

    resources "/posts", PostController, only: [] do
      resources "/comments", CommentController, only: [:create, :delete, :update]
    end

    resources "/sessions", SessionController, only: [:new, :create, :delete]

  end

  # Other scopes may use custom stacks.
  # scope "/api", PxblogWeb do
  #   pipe_through :api
  # end
end

lib/pxblog_web/views/layout_view.ex
defmodule PxblogWeb.LayoutView do
  use PxblogWeb, :view

  def current_user(conn) do
    Plug.Conn.get_session(conn, :current_user)
  end
end

lib/pxblog_web/templates/layout/alerts.html.eex
<div class="row alerts">
  <%= if flash = get_flash(@conn, :info) do %>
    <div class="success callout alert-info" role="alert">
      <%= flash %>
    </div>
  <% end %>

  <%= if flash = get_flash(@conn, :error) do %>
    <div class="alert callout alert-error" role="alert">
      <%= flash %>
    </div>
  <% end %>
</div>

lib/pxblog_web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <%= render "head.html", conn: @conn %>

  <body>
    <%= render "navigation.html", conn: @conn %>

    <section class="main-content row expanded">
      <%= render "alerts.html", conn: @conn %>

      <div class="row content">
        <%= render @view_module, @view_template, assigns %>
      </div>
    </section>

    <%= render "script.html", conn: @conn %>
  </body>
</html>

lib/pxblog_web/templates/layout/head.html.eex
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="description" content="A Tech Blog Written in Elixir and Phoenix">
  <meta name="author" content="Musa Juma">
  <%= if current_user = @conn.assigns[:current_user] do %>
    <%= tag :meta, name: "channel_token", content: Phoenix.Token.sign(@conn, "user", current_user.id) %>
  <% end %>

  <title>Musa Tech Blog</title>
  <link rel="stylesheet" href="<%= Routes.static_path(@conn, "/css/app.css") %>
</head>

lib/pxblog_web/templates/layout/navigation.html.eex
<div class="top-bar">
  <div class="top-bar-left">
    <ul class="menu">
      <li class="logo">
        Phoenix Tech Blog
      </li>
      <li>
        <%= link "Home", to: Routes.page_path(@conn, :index) %>
      </li>
      <li>
        <%= link "Posts", to: Routes.post_path(@conn, :index) %>
      </li>
      <%= if current_user = @conn.assigns[:current_user] do %>
        <li>
          <%= link "My Posts", to: Routes.user_post_path(@conn, :index, current_user.id) %>
        </li>
        <li>
          <%= link "New Post", to: Routes.user_post_path(@conn, :new, current_user.id) %>
        </li>
      <% end %>
    </ul>
  </div>
  <div class="top-bar-right">
    <ul class="menu">
        <%= if current_user = @conn.assigns[:current_user] do %>
          <li>
            <%= link current_user.username, to: Routes.user_path(@conn, :edit, current_user.id) %>
          </li>
          <li>
            <%= link "Logout", to: Routes.session_path(@conn, :delete, current_user.id), method: :delete, class: "button alert" %>
          </li>
        <% else %>
          <li>
            <%= link "Login", to: Routes.session_path(@conn, :new), class: "button" %>
          </li>
        <% end %>
      </li>
    </ul>
  </div>
</div>

lib/pxblog_web/templates/layout/script.html.eex
<script src="<%= Routes.static_path(@conn, "/js/app.js") %>"></script>
<script type="text/javascript">
  $(function() {
    $(document).foundation();
  });
</script>

lib/pxblog_web/templates/layout/splash.html.eex
<!DOCTYPE html>
<html lang="en">
  <%= render "head.html", conn: @conn %>

  <body>
    <%= render "navigation.html", conn: @conn %>

    <section class="main-content row expanded">
      <%= render "alerts.html", conn: @conn %>

      <section class="text-center image-overlay row content">
        <%= render @view_module, @view_template, assigns %>
      </section>

      <section class="about expanded row">
        <div class="social-media text-center">
          <a href="https://twitter.com/jmusa254"><i class="fi-social-twitter"></i></a>
          <a href="https://web.facebook.com/juma.musa.737"><i class="fi-social-facebook"></i></a>
        </div>
      </section>
    </section>

    <%= render "script.html", conn: @conn %>
  </body>
</html>